### PR TITLE
Day 05 react polymer concurrently

### PR DESCRIPTION
**Pull request by Journeycorner**
Execution time went down from ~580ms to ~175ms on my quad core machine.

### CODE REVIEW

**Comment by BurntSushi** [comment]
Thanks! Neat! Unfortunately, I'm going to have to pass. As the README says, I specifically did not focus on performance because it's an unending rabbit hole with no obvious benchmarks.

This repo is more for folks just learning Rust and asking questions.

**Comment by Journeycorner** [comment]
I see! Speaking of questions of people learning Rust: do you know repos of tweaked solutions? I come from Java and I am curious about "low level" tuning.

**Comment by BurntSushi** [comment]
No, sorry. You might have better luck here: https://www.reddit.com/r/adventofcode/

**Comment by smarnach** [comment]
@Journeycorner If you are interested in an efficient solution for this particular problem, [I pasted mine here](https://gist.github.com/smarnach/6fc075561ef880cc1a58d5d2c63347e6). It finishes in something like 5ms single-threadedly on my old laptop, and it's also far simpler than any other solution I saw, weighing roughly 20 lines of Rust.

**Pull request closed without merging**
